package com.fhqinui.frize.dal.mybatis.mapper.sys;

import com.fhqinui.frize.common.entity.sys.SysMenu;
import com.fhqinui.frize.common.entity.sys.SysMenuExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SysMenuMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_menu_
     *
     * @mbggenerated 2015-07-31 10:35:49
     */
    int countByExample(SysMenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_menu_
     *
     * @mbggenerated 2015-07-31 10:35:49
     */
    int deleteByExample(SysMenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_menu_
     *
     * @mbggenerated 2015-07-31 10:35:49
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_menu_
     *
     * @mbggenerated 2015-07-31 10:35:49
     */
    int insert(SysMenu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_menu_
     *
     * @mbggenerated 2015-07-31 10:35:49
     */
    int insertSelective(SysMenu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_menu_
     *
     * @mbggenerated 2015-07-31 10:35:49
     */
    List<SysMenu> selectByExample(SysMenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_menu_
     *
     * @mbggenerated 2015-07-31 10:35:49
     */
    SysMenu selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_menu_
     *
     * @mbggenerated 2015-07-31 10:35:49
     */
    int updateByExampleSelective(@Param("record") SysMenu record, @Param("example") SysMenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_menu_
     *
     * @mbggenerated 2015-07-31 10:35:49
     */
    int updateByExample(@Param("record") SysMenu record, @Param("example") SysMenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_menu_
     *
     * @mbggenerated 2015-07-31 10:35:49
     */
    int updateByPrimaryKeySelective(SysMenu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_menu_
     *
     * @mbggenerated 2015-07-31 10:35:49
     */
    int updateByPrimaryKey(SysMenu record);
}